#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int controller_layout_id = 2130771968;
			
			// aapt resource value: 0x7f010008
			public const int default_artwork = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int fastforward_increment = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int player_layout_id = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int resize_mode = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int rewind_increment = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int show_timeout = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int surface_type = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int use_artwork = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int use_controller = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int exo_media_button_height = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int exo_media_button_width = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int exo_controls_fastforward = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int exo_controls_next = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int exo_controls_pause = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int exo_controls_play = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int exo_controls_previous = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exo_controls_rewind = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070018
			public const int MyButton = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int MyTest = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int MyVideo = 2131165207;
			
			// aapt resource value: 0x7f070000
			public const int exo_artwork = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int exo_content_frame = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int exo_controller_placeholder = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int exo_duration = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int exo_ffwd = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int exo_next = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int exo_overlay = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int exo_pause = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int exo_play = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int exo_position = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int exo_prev = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int exo_progress = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int exo_rew = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int exo_shutter = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int exo_subtitles = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int fill = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int fit = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int fixed_height = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int fixed_width = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int none = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int surface_view = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int texture_view = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int exo_playback_control_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int exo_simple_player_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040008
			public const int ApplicationName = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int Hello = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int exo_controls_fastforward_description = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int exo_controls_next_description = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int exo_controls_pause_description = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int exo_controls_play_description = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int exo_controls_previous_description = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int exo_controls_rewind_description = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int exo_controls_stop_description = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int ExoMediaButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int ExoMediaButton_FastForward = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ExoMediaButton_Next = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ExoMediaButton_Pause = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ExoMediaButton_Play = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ExoMediaButton_Previous = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int ExoMediaButton_Rewind = 2131034118;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AspectRatioFrameLayout = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int AspectRatioFrameLayout_resize_mode = 0;
			
			public static int[] PlaybackControlView = new int[] {
					2130771968,
					2130771969,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int PlaybackControlView_controller_layout_id = 0;
			
			// aapt resource value: 1
			public const int PlaybackControlView_fastforward_increment = 1;
			
			// aapt resource value: 2
			public const int PlaybackControlView_rewind_increment = 2;
			
			// aapt resource value: 3
			public const int PlaybackControlView_show_timeout = 3;
			
			public static int[] SimpleExoPlayerView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int SimpleExoPlayerView_controller_layout_id = 0;
			
			// aapt resource value: 8
			public const int SimpleExoPlayerView_default_artwork = 8;
			
			// aapt resource value: 1
			public const int SimpleExoPlayerView_fastforward_increment = 1;
			
			// aapt resource value: 2
			public const int SimpleExoPlayerView_player_layout_id = 2;
			
			// aapt resource value: 3
			public const int SimpleExoPlayerView_resize_mode = 3;
			
			// aapt resource value: 4
			public const int SimpleExoPlayerView_rewind_increment = 4;
			
			// aapt resource value: 5
			public const int SimpleExoPlayerView_show_timeout = 5;
			
			// aapt resource value: 6
			public const int SimpleExoPlayerView_surface_type = 6;
			
			// aapt resource value: 7
			public const int SimpleExoPlayerView_use_artwork = 7;
			
			// aapt resource value: 9
			public const int SimpleExoPlayerView_use_controller = 9;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
